conda/recipes/cuopt-server/recipe.yaml
conda/recipes/cuopt-sh-client/recipe.yaml

The `cuopt-sh-client` and `cuopt-server` packages are pure Python.
However, their conda packages are not technically built as `noarch: python` because of some historical limitations in RAPIDS build workflows (to be addresses as part of https://github.com/rapidsai/build-planning/issues/43).
As a result, 1 of those packages is published for each combination of `(Python minor version, CPU architecture)` supported by RAPIDS. See, for example, https://anaconda.org/nvidia/cuopt-server/files?version=25.05.00
For as long as we're doing that, those packages should have a constraint on `python`, so that (for example) only 1 package matches for a given `(Python minor version, CPU architecture)`.
This does that.

include Python constraints for pure-Python conda packages

---

python/cuopt_server/cuopt_server/utils/job_queue.py

Only consider the first two fields in the client version. Without this change the service will report that the version is a bad format, which is not necessary in this case.

allow long client version in service version check'

---

cpp/src/dual_simplex/branch_and_bound.cpp
cpp/src/linear_programming/utilities/logger_init.hpp
cpp/src/mip/presolve/trivial_presolve.cuh

This PR fixes two bugs discovered while testing the AMPL interface:
1) We weren't correctly calculating the objective constant when presolve eliminated variables on a maximization problem.
Thanks to Alice for the quick fix!
2) We had an undefined memory access on the number of nodes and simplex iterations when solving a MIP at the root node.

Fix obj constant on max. Fix undefined memory access at root

---

cpp/include/cuopt/linear_programming/constants.h
cpp/include/cuopt/linear_programming/mip/solver_settings.hpp
cpp/include/cuopt/linear_programming/pdlp/solver_settings.hpp
cpp/src/linear_programming/solve.cu
cpp/src/math_optimization/solver_settings.cu
cpp/src/mip/problem/write_mps.cu
cpp/src/mip/solve.cu
cpp/tests/mip/doc_example_test.cu
docs/cuopt/source/cuopt-c/lp-milp/lp-milp-c-api.rst
docs/cuopt/source/lp-milp-settings.rst
python/cuopt/cuopt/linear_programming/solver/solver_parameters.pyx
python/cuopt/cuopt/tests/linear_programming/test_lp_solver.py

This PR adds the string parameter CUOPT_USER_PROBLEM_FILE = "user_problem_file".  By default the parameter is the empty string "". If the parameter is set by the user to something other than the empty string, we will write out an MPS file containing the LP or MIP. 
This is very useful when trying to debug interfaces like CVXPY where the interface between CVXPY and cuOpt may have performed transformation to the user problem. This allows us to reproduce failures on the engine side directly from the MPS file without needing Python scripts.

Write out mps file containing user problem. Useful for debugging

---

.github/workflows/build.yaml
.github/workflows/nightly.yaml

This adds jobs to push/publish nightly packages and also fixes nightly testing to wait for the build workflow to complete first.

Enable nightly package publishing and fix nightly testing workflow

---

.github/workflows/build.yaml
.github/workflows/nightly.yaml
README.md
cpp/include/cuopt/linear_programming/constants.h
cpp/include/cuopt/linear_programming/mip/solver_settings.hpp
cpp/include/cuopt/linear_programming/pdlp/solver_settings.hpp
cpp/include/cuopt/linear_programming/utilities/cython_solve.hpp
cpp/src/dual_simplex/branch_and_bound.cpp
cpp/src/linear_programming/solve.cu
cpp/src/linear_programming/utilities/cython_solve.cu
cpp/src/linear_programming/utilities/logger_init.hpp
cpp/src/math_optimization/solver_settings.cu
cpp/src/mip/presolve/trivial_presolve.cuh
cpp/src/mip/problem/write_mps.cu
cpp/src/mip/solve.cu
cpp/tests/mip/doc_example_test.cu
docs/cuopt/source/cuopt-c/lp-milp/lp-milp-c-api.rst
docs/cuopt/source/cuopt-python/quick-start.rst
docs/cuopt/source/cuopt-server/quick-start.rst
docs/cuopt/source/index.rst
docs/cuopt/source/introduction.rst
docs/cuopt/source/lp-features.rst
docs/cuopt/source/lp-milp-settings.rst
docs/cuopt/source/milp-features.rst
docs/cuopt/source/thirdparty_modeling_languages/index.rst
python/cuopt/cuopt/linear_programming/solver/solver_parameters.pyx
python/cuopt/cuopt/tests/linear_programming/test_lp_solver.py
python/cuopt_server/cuopt_server/utils/job_queue.py

Branch 25.08 merge 25.05

---

.github/workflows/nightly.yaml
.github/workflows/test.yaml

`jq` option doesn't work with gh workflow command and needs to be move to separate command.

Fix nightly build which is failing on jq request

---

python/cuopt_self_hosted/cuopt_sh_client/cuopt_self_host_client.py
python/cuopt_server/cuopt_server/cuopt_service.py
python/cuopt_server/cuopt_server/utils/job_queue.py

The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
This small PR resolves those warnings. It also fixes a few typos along the way.

Migrate to modern logger interface

---

cpp/include/cuopt/linear_programming/mip/solver_settings.hpp
cpp/src/mip/diversity/diversity_manager.cu
cpp/src/mip/presolve/bounds_presolve.cu
cpp/src/mip/presolve/bounds_update_helpers.cuh
cpp/src/mip/problem/problem.cu
cpp/src/mip/problem/problem_helpers.cuh
cpp/tests/mip/unit_test.cu

Updating the constraint bounds based on minimal and maximal activity can sometimes cause the update constraint lower bounds to be greater than constraint upper bounds even if the constraint is feasible within tolerance.
This PR fixes the constraint bounds to the same value if this happens.

Fix inversion of constraint bounds in conditional bounds presolve

---

CONTRIBUTING.md

This simplifies and update source build instructions.

Update Source build instructions

---

cpp/src/mip/problem/problem.cu
cpp/src/mip/problem/problem_helpers.cuh
cpp/src/mip/solve.cu
cpp/tests/mip/empty_fixed_problems_test.cu
cpp/tests/mip/termination_test.cu
datasets/mip/empty-max-problem-objective-vars.mps
datasets/mip/empty-problem-objective-vars.mps
datasets/mip/trivial-presolve-no-obj-vars.mps

This PR fixes a crash occurring when solving a model containing no constraints but some variables. 
Also ensures the correct objective value is computed in this scenario
Closes #104

Fix crash on models with variables but no constraints

---

cpp/src/linear_programming/step_size_strategy/adaptive_step_size_strategy.cu
cpp/src/linear_programming/step_size_strategy/adaptive_step_size_strategy.hpp
cpp/src/linear_programming/utilities/cython_solve.cu
cpp/src/utilities/unique_pinned_ptr.hpp

This PR aims at fixing the intermittent error we are seeing in CI on the Python Batch PDLP test.
Previous PR were trying to achieve the same while not solving the root cause: work being pushed to the default stream.
As described here: https://github.com/NVIDIA/cccl/issues/5027 creating a thrust::host pinned memory allocator is incorrectly launching work on the GPU on the default stream which might happen during a graph capture, creating an error.
To fix it, we now use a std::unique_ptr with a custom allocator to allocate host pinned memory.
This allows us to go back to a non blocking stream when using batch mode.

Fix batch graph capture issue caused by pinned memory allocator

---

ci/build_wheel.sh

This PR adds changes which updates version based on git tag so that nightly and release packages can  be differentiated.
closes #167 
- Testing 

Fix versioning for nightly and release package 

---

cpp/src/mip/diversity/diversity_manager.cu
cpp/src/utilities/scope_guard.hpp
cpp/tests/linear_programming/c_api_tests/c_api_tests.cpp

This PR fixes a bug causing solving time to be incorrectly reported on problems that are solved by B&B pre-emption before the main GPU solver loop runs.

Fix incorrect reported solving time

---

cpp/src/dual_simplex/presolve.cpp
cpp/src/dual_simplex/presolve.hpp
cpp/src/dual_simplex/scaling.cpp
cpp/src/dual_simplex/solve.cpp
cpp/tests/dual_simplex/unit_tests/solve.cpp

Fixes a bug in how dual slacks (reduced costs) were unscaled. 
Fixes #183 : dual simplex produces the wrong sign for dual variables with >= constraints
closes #183
- Testing 
- [] Added new documentation

Fix bug in scaling of dual slacks and sign of dual variables for >= constraints

---

cpp/CMakeLists.txt
cpp/src/linear_programming/utilities/logger_init.hpp

This fixes an issue of formatting when writing to a log file, it was always writing with the default format regardless of the log level. Whereas, for builds on debug and higher levels we want timestamps.

Fix logging levels

---

cpp/tests/mip/feasibility_jump_tests.cu

This disables flaky test which fails more often blocking CI
#214 
- Testing 

Disable feasibility jump test for one of the dataset

---

cpp/src/linear_programming/utilities/problem_checking.cu
cpp/src/mip/diversity/diversity_manager.cu
cpp/src/mip/utils.cuh
cpp/tests/mip/CMakeLists.txt

This fixes a bug on the variable violation check where the check is done on a wrong size. This also fixes the bug in set_simplex_solution in which the lp_optimal_solution might not be allocated by the time simplex found a solution, and another bug of cuda_set_device was called after some GPU operations in assert mode.
closes #221

Fix bug on initial solution size in the check and cuda set device order

---

.github/workflows/nightly.yaml

Bumps the version of actions/checkout in nightly.yaml to the latest, v4 - https://github.com/actions/checkout?tab=readme-ov-file#checkout-v4
- Testing

Bump actions/checkout in nightly.yaml to v4

---

cpp/CMakeLists.txt
cpp/src/mip/diversity/assignment_hash_map.cu
cpp/src/mip/solution/solution.cu
cpp/src/utilities/macros.cuh
cpp/tests/mip/bounds_standardization_test.cu
cpp/tests/mip/elim_var_remap_test.cu

Raft defines `RAFT_CHECK_CUDA` depending on if we run in release/Debug mode https://github.com/rapidsai/raft/blob/branch-25.06/cpp/include/raft/util/cuda_rt_essentials.hpp#L78-L82.
In cuopt we have a special mode "assert" that undefines `NDEBUG` to run with optimizations but still enable runtime checks. https://github.com/rapidsai/raft/blob/branch-25.06/cpp/include/raft/util/cuda_rt_essentials.hpp#L78-L82
The first version of `RAFT_CHECK_CUDA` uses the stream argument therefore in debug mode and assert mode we should catch that error. However unsetting `NDEBUG` in our header results in `NDEBUG` being undefined in cuopt but still defined for our dependencies. So we were calling the wrong implementation of `RAFT_CUDA_CHECK`. To undefine `NDEBUG` in both cuopt and our dependencies we have to …

Unset NDEBUG in cmake in assert mode

---

cpp/src/dual_simplex/basis_solves.cpp
cpp/src/dual_simplex/phase2.cpp
cpp/src/dual_simplex/right_looking_lu.cpp

This PR includes two fixes:
* Basis repair was failing due to a bug in the right-looking LU where the column permutation was not fully populated when the basis was rank deficient. 
* When computing delta x using a hypersparse solve the solution vector sometimes did not contain a nonzero coefficient associated with the basic leaving index. This was an issue, as we divide by that coefficient to compute the primal step length.  This coefficient may have been missing due to the numerical drop tolerances. To recover from this we perform a regular solve. If the coefficient is small, but nonzero, we can recover. 
In addition this PR adds the option to use threshold rook pivoting inside the right-looking LU factorization. TRP is rank-revealing. However, it produces factors L and U with more fill …

Fix a bug in basis repair. Recover from numerical issues in primal update.

---

cpp/src/dual_simplex/basis_updates.cpp

When using the new middle product form for basis updates, we can sometimes get a mu = 0. This leads to infs and then nans and then out of bound memory accesses.
A simple fix is to force a refactorization of the basis when this happens.
This fixes #252

Fix a segfault on bnatt500 due to small mu leading to inf/nan

---

cpp/src/dual_simplex/presolve.cpp

Dual simplex presolve had an assert to prevent it from removing an empty column with a variable with an infinite bounds.
This PR removes the assert and just skips variables with infinite bounds.
This fixes Issue #270

Don't remove empty columns with infinite bounds

---

benchmarks/linear_programming/utils/get_datasets.py
cpp/tests/linear_programming/pdlp_test.cu

The website is  down and dataset can't be pulled

Skip downloading netlib data

---

cpp/src/mip/presolve/third_party_presolve.cpp
cpp/tests/linear_programming/pdlp_test.cu
cpp/tests/linear_programming/utilities/pdlp_test_utilities.cuh

This PR updates the settings for root node papilo presolve.
We reverted previous changes to instead use default settings from Papilo.
These settings allow us to solve more problems with better performance.
We also enable singleton stuffing which after further testing has no negative impact on accuracy and improves the final reduction.
Regarding post-solve accuracy issues we will be addressing them in a follow up PR.

Enable singleton stuffing and use papilo default params

---

.github/workflows/build_images.yaml
.github/workflows/build_test_publish_images.yaml
.github/workflows/test_images.yaml
ci/docker/Dockerfile
python/cuopt_server/cuopt_server/utils/utils.py

Adding commit SHA for future reference
- Testing

Add Commit Sha to container for reference

---

python/libcuopt/libcuopt/load.py

While loading libcuopt using load, sometimes due to a missing dependent library we get error as libcuopt.so is missing even though libcuopt.so is present but some other dependency is missing.
This PR adds a warning in such cases so it doesn't fail in the corner cases, but provide a better details through a warning.
closes #340
- Testing

Warn in case a dependent library is not found in libcuopt load 

---

.github/workflows/build_test_publish_images.yaml
README.md
ci/docker/Dockerfile
dependencies.yaml
docs/cuopt/source/cuopt-c/quick-start.rst
docs/cuopt/source/cuopt-python/quick-start.rst
docs/cuopt/source/cuopt-server/quick-start.rst
python/libcuopt/CMakeLists.txt

- This PR adds support for cuda 13 container for nightly and release
- Also updates python version to 3.13
- Also cuda-toolkits have stopped using cu13 suffixes and they need to be fixed in dependencies
- This also requires addition to RPATH since the paths are different for cu13
- Testing

Add support for cuda13 container and fix cuda13 lib issues in wheel

---

benchmarks/linear_programming/cuopt/run_mip.cpp

The previous VRAM fix PR left a limiting_resource_adaptor in the code limiting runs on multiple GPUs to 6GB of VRAM. This was not meant to be part of the push, and this PR fixes this mistake.

Remove limiting_resource_adaptor leftover

---

conda/environments/all_cuda-129_arch-aarch64.yaml
conda/environments/all_cuda-129_arch-x86_64.yaml
conda/environments/all_cuda-130_arch-aarch64.yaml
conda/environments/all_cuda-130_arch-x86_64.yaml
conda/recipes/cuopt-server/recipe.yaml
dependencies.yaml
python/cuopt_server/pyproject.toml

Fixes two small packaging issues with `cuopt-server`:
* removes unnecessary dependency on `httpx` (`cuopt-server` does not use this)
* declares dependency on `psutil` (this is declared in wheels but was missing in conda packages)
Was looking at the conda recipes and checked these things, similar to this:
```shell
git grep httpx
```
- Testing

cuopt-server: update dependencies (drop httpx, add psutil)

---

benchmarks/README.md
benchmarks/linear_programming/utils/get_datasets.py

This dataset was disabled in PR #335 since the website was down, the services have been restored as of now, so enabling this back.
And also adding details to README to benchmark mittleman and miplib.
#335 
- Testing

Enable miplib datasets which was disabled and also update README

---

ci/utils/install_boost_tbb.sh

Adding dnf -y update pull new repo through which new mirrors can be accessed to pull libs
- Testing

Fix issue stemming because Rocky 8.10 is EOL and replaced by 8.11

---

cpp/src/dual_simplex/branch_and_bound.cpp

This PR fixes the delayed termination of the branch-and-bound algorithm after reaching the time limit.

Fixed delayed termination after timeout

---

conda/recipes/libcuopt/recipe.yaml
cpp/CMakeLists.txt
cpp/src/dual_simplex/device_sparse_matrix.cuh
cpp/src/dual_simplex/sparse_cholesky.cuh
cpp/src/utilities/driver_helpers.cuh
cpp/src/utilities/macros.cuh

This PR enables stream concurrency by sharing SM resources between PDLP and Barrier. It fixes compile errors that occured while merging https://github.com/NVIDIA/cuopt/pull/272

Enable green context in Barrier

---

benchmarks/linear_programming/cuopt/run_mip.cpp
cpp/src/mip/feasibility_jump/feasibility_jump_impl_common.cuh
cpp/src/mip/feasibility_jump/feasibility_jump_kernels.cu
cpp/src/mip/feasibility_jump/fj_cpu.cu
cpp/tests/linear_programming/c_api_tests/c_api_tests.cpp

This PR modifies CPUFJ to periodically recompute LHS and objective values to eliminate accumulated running errors. This check is also performed again before saving any potential best incumbent. This should help eliminate the occasional 'external solution infeasible' logs.

More numerically robust CPUFJ feasibility checking

---

cpp/src/mip/feasibility_jump/feasibility_jump.cuh
cpp/src/mip/feasibility_jump/feasibility_jump_kernels.cu
cpp/src/mip/feasibility_jump/fj_cpu.cu
cpp/src/mip/feasibility_jump/fj_cpu.cuh
cpp/src/mip/feasibility_jump/load_balancing.cuh

This PR fixes an inconsistent calculation for an assert() test causing it to be triggered due to numerical issues. Additional improvements to prevent runoff are also included

Further CPUFJ assert and numerical fixes
